export const color = {
  text: '#000',
  transparent: 'rgba(0, 0, 0, 0)',
  background: 'white',
  lightText: '#5C5C5C',
  disable: '#E4E4E4',
  primary: '#0099D8',
  primaryDarker: 'blue',
  line: 'blue',
  white: 'white',
  light: 'white',
  activeGreen: '#8C6F09',
  dimBackground: 'rgba(0, 0, 0, 0.3)',
  darkDimBackground: 'rgba(0,0,0,0.7)',
  blue: 'blue',
  error: '#ED3843',
  black: 'black',
  darkBg: '#000',
  golden: 'yellow',
  midBlack: '#454545',
  darkRed: 'red',
  lightGray: '#DBDBDB',
};

export type ColorType = keyof typeof color;
